### ISSUE TITLE
symfpu cannot be compiled

### ISSUE THREAD

**Issue by johndoe888** [martin-cs/CVC4#2]
Martin,

I tried compiling your symfpu branch. It stops with several of the following errors:

    CXXLD    libcvc4.la
symfpu/baseTypes/.libs/cvc4_symbolic.o: In function `metaKindOf':
/home/jd/tools/cvc4-with-fp/builds/x86_64-unknown-linux-gnu/production/src/../../../../src/symfpu/baseTypes/cvc4_symbolic.cpp:64: multiple definition of `symfpu::cvc4_symbolic::bitVector<false>::minValue(unsigned int const&)'

symfpu/baseTypes/.libs/cvc4_symbolic.o:/home/jd/tools/cvc4-with-fp/builds/x86_64-unknown-linux-gnu/production/src/../../../../src/symfpu/baseTypes/cvc4_symbolic.cpp:64: first defined here
symfpu/baseTypes/.libs/cvc4_symbolic.o: In function `bool CVC4::kind::metakind::NodeValueCompare::compare<true>(CVC4::expr::NodeValue const*, CVC4::expr::NodeValue const*)':

/home/jd/tools/cvc4-with-fp/builds/x86_64-unknown-linux-gnu/production/src/../../../../src/symfpu/baseTypes/cvc4_symbolic.cpp:35: multiple definition of `symfpu::cvc4_symbolic::traits::RNE()'

Can you help me with this?

**Comment by florianschanda** [comment]
I can build and this is my approach:

`export CXXFLAGS="-march=native -std=gnu++98"`

Note that in particular the -std is needed on gcc6. We use the following configure flags:

```
            --disable-shared \
            --enable-optimized \
            --with-build=production \
            --without-readline \
            --disable-debug-symbols \
            --disable-proof \
            --disable-maintainer-mode
```

**Comment by johndoe888** [comment]
Great. This worked.

**Comment by florianschanda** [comment]
Great, good to know :)

**Comment by johndoe888** [comment]
OK. The binary is compiled and a first simple floatingpoint test with an smt2 file worked. 

A new problem popped up, when compiling a c program using cvc4:
```
/home/jd/local/include/cvc4/util/floatingpoint.h:122:48: fatal error: cvc4/symfpu/baseTypes/cvc4_literal.h: No such file or directory
 #include <cvc4/symfpu/baseTypes/cvc4_literal.h>
                                                ^
```
Seems like there is something wrong with the Makefile maybe?

**Comment by johndoe888** [comment]
When manually copying all symfpu header files to the needed include directory the next problem pops up:

```
/home/jd/local/include/cvc4/symfpu/baseTypes/cvc4_literal.h:41:37: fatal error: symfpu/utils/properties.h: No such file or directory
 #include "symfpu/utils/properties.h"
                                     ^
```

I think the problem may be a shortened include command which says:
`#include "symfpu/utils/properties.h"` and not `#include "cvc4/symfpu/utils/properties.h"`

What do you think?

**Comment by johndoe888** [comment]
OK, when copying all symfpu headers to my include and prefixing those include directives with "cvc4/" compiling my bindings to cvc4 work until linking, because no shared libraries were created. This is because of using option "--disable-shared" as suggested by @florianschanda, I guess.

So, in the end I am back to my original problem of multiple definitions:
```
CXXLD    libcvc4.la

symfpu/baseTypes/.libs/cvc4_symbolic.o: In function metaKindOf': /home/jd/tools/cvc4-with-fp/builds/x86_64-unknown-linux-gnu/production/src/../../../../src/symfpu/baseTypes/cvc4_symbolic.cpp:64: multiple definition ofsymfpu::cvc4_symbolic::bitVector::minValue(unsigned int const&)'
symfpu/baseTypes/.libs/cvc4_symbolic.o:/home/jd/tools/cvc4-with-fp/builds/x86_64-unknown-linux-gnu/production/src/../../../../src/symfpu/baseTypes/cvc4_symbolic.cpp:64: first defined here
symfpu/baseTypes/.libs/cvc4_symbolic.o: In function `bool CVC4::kind::metakind::NodeValueCompare::compare(CVC4::expr::NodeValue const*, CVC4::expr::NodeValue const*)':
/home/jd/tools/cvc4-with-fp/builds/x86_64-unknown-linux-gnu/production/src/../../../../src/symfpu/baseTypes/cvc4_symbolic.cpp:35: multiple definition of `symfpu::cvc4_symbolic::traits::RNE()'
```

Can somebody comment on this one?

**Comment by florianschanda** [comment]
Honestly, I have no experience in linking against CVC4, I only ever use it as a standalone tool.

**Comment by martin-cs** [comment]
On Fri, 2017-02-03 at 09:25 -0800, Florian Schanda wrote:
> Honestly, I have no experience in linking against CVC4, I only ever use it as a standalone tool.

I haven't tried building this branch as a library, so I'm not entirely
surprised it doesn't work.  The branch is a "work in progress" and
having header files in a separate directory was meant to be a temporary
state of affairs until we were looking to merge it to trunk.

I'll put it on the TODO list.

**Comment by johndoe888** [comment]
Is there anything I can do to help you with this?

**Comment by martin-cs** [comment]
Yes!

Floating-point support is now in master.
./contrib/get-symfpu
./configure --with-symfpu

Please use and let me know how you get on!  Issues to the main CVC4 repository, user experience reports to me by e-mail.
