### ISSUE TITLE
Floating-point literals

### ISSUE THREAD

**Issue by wintersteiger** [martin-cs/CVC4#5]
Is this really unsupported or am I using the wrong fork/branch?

To this:

```
(set-logic QF_FP)
(declare-fun x () (_ FloatingPoint 8 24))
(assert (= x (fp #b0 #x80 #b10000000000000000000000)))
(check-sat)
```

CVC (symfpu and 1.7) replies:

```
(error "Unimplemented code encountered
void CVC4::FloatingPointLiteral::unfinished() const
/mnt/f/dev/cvc4-symfpu/src/util/floatingpoint.cpp:462
Floating-point literals not yet implemented.")
```

**Comment by martin-cs** [comment]
On Tue, 2019-07-02 at 03:14 -0700, Christoph M. Wintersteiger wrote:
> Is this really unsupported or am I using the wrong fork/branch?
<snip>

This should be supported in the main CVC4 master.  Everything has been
merged so the branches here are a little ... historic.

What configuration options did you use?  `contrib/get-symfpu` will get
the right version and then `configure.sh --symfpu` will build with it. 
Full instructions in `INSTALL.md`.

Cheers,
 - Martin

**Comment by wintersteiger** [comment]
Found the instructions in the meanwhile - I assumed that sympfu branch would include it by default, but it doesnt'.

**Comment by martin-cs** [comment]
On Tue, 2019-07-02 at 04:54 -0700, Christoph M. Wintersteiger wrote:
> Found the instructions in the meanwhile - I assumed that sympfu
> branch would include it by default, but it doesnt'.

No; sorry.  I should probably delete this branch as it is now merged.

Cheers,
 - Martin
